apiVersion: v1
kind: Secret
metadata:
  name: uc4-minio-configuration
  namespace: uc4-minio
data:
  config.env: >-
    <BASE64>
    export MINIO_ROOT_USER="$UC4_MINIO__ROOT_USER"
    export MINIO_ROOT_PASSWORD="$UC4_MINIO__ROOT_PASSWORD"
    </BASE64>
type: Opaque
