# You can create this secret by running
#    kubectl create secret docker-registry ghcr-secret \
#      --docker-server=ghcr.io \
#      --docker-username=... \
#      --docker-password=... \
#      --dry-run=client -o yaml

apiVersion: v1
kind: Secret
metadata:
  name: uc4-workload-github
  namespace: uc4-workload
data:
  .dockerconfigjson: >-
    <BASE64>
    {
      "auths": {
        "ghcr.io": {
          "username": "$UC4_WORKLOAD__GITHUB_USER",
          "password": "$UC4_WORKLOAD__GITHUB_TOKEN",
          "auth": "<BASE64>$UC4_WORKLOAD__GITHUB_USER:$UC4_WORKLOAD__GITHUB_TOKEN</BASE64>"
        }
      }
    }
    </BASE64>
type: kubernetes.io/dockerconfigjson
