---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: uc4-workload-github
  namespace: uc4-workload
spec:
  encryptedData:
    .dockerconfigjson: AgAZyerMo0aMP/56A8qYbju8IZWpSXdairjGbl+nMlhsFT965u+jb5XvwuISJ/fV7r/yPHyqhhQHUqFFH8/5D4oVFplo6fSkpJ4BTePBPeqMkKkhLkOI7k+sz8L+TmKJjAEFDNoTUiXY8oTOxJv91FAUHNRCSd/F5G2cU+fNF4CRQTDrXivrRGcdBkEB7dMMH+gW1Uo0a5GK6J3BnZwt23gOWNZVfdNLqf42PiqRZLwfk8dTDzIyD6sWT+4jCNKq/1jJ8V5ywT2QtDqy+SzI3w0GYddJO8ogLi/KODrwegcf706H56HobSFWWUfpj7IKtiwXXmX3Ur0NC3qRY+D1NPh7RhQ/bNFEzhX80gwRyRMiEp1a2veObxwyOdKn11drREmNut6W5RFwi9vIIZVCH702U1uyIyhQXMP1BE8jK0gE2ZSr8Lo9rKpAzIbG6faut9qdrz10XNWygF73pCwfvurchsPscjXG552CtbxLzFA9O1bF7+gcd8QaPbCb6bCQGvLk/bAsNC9bJUOrjcpMR0+SnZlycmcTT2nYHPlLLdWjo7M5cr+vJh4cfK6mlhHdk/Pm/4i44t6YMCFTpmURpsOiKLsxRLgUKJasOuXKWDoT0rzlObDgu8jUWfxhEwJ+vnZjad8tOvjqoizYyoQPpuFTJ7mFspoQtsZTCp/1lSX+Y7Sacf3DFyUBl+khpZLeTtfuvVEPswa8b4LznrbQ7DLoXHI94f1ouPGYDyGqQrZIRRp0GjxuZP+/U8JG9p93dj96YrtCJVyprITAIVNNJBfjminiPnR/w+9l1QPZcsM6Gyma6dmGb+OvkZaiY+flgs2q6ZtZ3p2ZD/mvYjP9ShjMJSDGICCWpPextzxJ92NcS29MbSxKYflHtgZ3XnC1DzvkSHAWOFMbAhh8qpbq2xFgav6nzmzsbL8K9ZKO+EIz4N1fR55xoI6O
  template:
    metadata:
      creationTimestamp: null
      name: uc4-workload-github
      namespace: uc4-workload
    type: kubernetes.io/dockerconfigjson
