---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: uc4-minio-configuration
  namespace: uc4-minio
spec:
  encryptedData:
    config.env: AgABLQ8h9Z/fPgPAVEPQfQg9rrKS7JS8EYipoQdygK3RwN8RUajeUmqnzxg1mNvZmIXEvkJEtnw4BZYtulKSVjTRvBoSpE8V1DxBWAZGn/L2jNGEBQYe6f8/GALmH02+L3S+0yzlS5UTx57eaErUCpZDpjy0H1w1qiEdH7hk6aeeqV+5bSQF944tp2uBRAGp0azrYVQAKcH10XRZ4Z4VY8JbKAfUEKFOdMdTaVH2gABt1wKgiGG957Wdtehwl+5gMWXZm+GxhewQwzCdgr+uzG9RqJ2o+nl/ku+iQuTRjMDVilKl4Gg21EuuY6LlIe29exhNZDtPfdOerSViRgvC5JksmCwwcTRtB/ed/ma/kLZlDeFHZkf+NrOHGWF7DWRCfWxYq54Zki1eeei5OPIDSf4r3sn8/K3NW5294+4pF2eOgNayDmr3Luorv0m0Hi40VlXvEVgJhy1zr0AOR3/ECxJ/LkhIVw4TuNGyijAKd2XVqT3E03Ee6CA540ecVs5g5X/ZVyxc09sNeFUsD/eCXyNAiMfeDtY/kRPCZy/IGVld4kDb1O5XXcV1eG28Bys+cKGNPOPqymRIhrwEDKwEQ/dxRyTQbmmzQDN2khRJs6HEYQHStIPJIFB4TFfj1YULJUb3tj1AqB33ICdmVwAd3s/V7PGJIpa19x1hKvePL9xTNHAfctGYZGnDSdu/nTbMzDvdMR5EaeXWGdATwXvXkFWkjPjUe+4ENokqBda50ZU7jpfqwpk19Akxb2scPUcjXnLNDQCXY7m20ejEGOyAAwGhN5t9M3efGCYjYQVlCCwrFnA=
  template:
    metadata:
      creationTimestamp: null
      name: uc4-minio-configuration-2
      namespace: uc4-minio
    type: Opaque
