---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: uc4-minio-configuration
  namespace: uc4-minio
spec:
  encryptedData:
    config.env: AgAQyof1KY1VDo0VemhottJtlqm6rGTtWMXMKQaAkPA/TFtWfwEzLiwfoeRFh9zwlPC4nFvSXBDsO/L9wmZ7GNGFG+7uMB+4HwF2AjqppZniRaRkT8UpuowknDfVDRhvVGPRWZFMTpUTEg4GK5eG6t2ZqCH3U8q8i0uVV4oLuoNSs7ZktSAXHm28E+xeT3pW3aBUPj/w8x6u0UZ9koNC4D0C1G7B6Vxv/tJ0p4sFUirwPWmx7uqyJctTMDHJ7jaBM5H+RHqod0OqLJNOACKKXEUdHqvQ2cLihS0BBNbWZpzAnA37N2W7yqifnsR64ecjQiuwa6LnLHO2v1FLuy+Sqsimexc4n2BhNkshYCCp0Ki33JL5t/qBEOWlQtGK6RNhCc/TFInTtZl4Riz72Gz49uMhnIX5iR6XDVTzbYVEdGRbgSU5w0zfVHR47Mcf2UJGDrQADh7K3JBDyAI+Pp/MNhdc/MvoXCBe3HBc77bst/LXfB2HEUza9cT3oIozurJ1INiJlHj4w9ZfhOWpZZLcCBcXCoLyyzC/1EOt/5jrrg5DBW5A+Qp3AxVHuEfwgzZse07Wk8oBQaBgO8yafZSvsU7YyIED8/fgS7sZntzz6wd9z5BZ0VA8BrXxMlyzDE33U4u2C7zSULIxKhgoQ6KwGiXfZRMJdThzphtJ31U8wzhzNjOfwEDObBaoQ9WCQDXaakpJAhjhYQCiSHoDDPB6b06m76GtldEawIHoniC1d7+W0NCs1MsMZ7Jx/7ZLqTVYPgPJmRrmIkoCyWw4lFJP4E5TBGTxMdxhUVs9PnnO7ZrG42o=
  template:
    metadata:
      creationTimestamp: null
      name: uc4-minio-configuration
      namespace: uc4-minio
    type: Opaque
